export const tiposIntervencao = [
{codigo:1,itens:'FREIOS'},
{codigo:2,itens:'DIREÇÃO'},
{codigo:3,itens:'PNEU FURADO TRAÇÃO'},
{codigo:4,itens:'PNEU FURADO DIREÇÃO'},
{codigo:5,itens:'PNEU FURADO CARRETA/DOLLY'},
{codigo:6,itens:'PNEU GASTO TRAÇÃO'},
{codigo:7,itens:'PNEU GASTO DIREÇÃO'},
{codigo:8,itens:'PNEU GASTO CARRETA/DOLLY'},
{codigo:9,itens:'MANGUEIRA DO CLAMPS'},
{codigo:10,itens:'MANGUEIRA DA TORRE'},
{codigo:11,itens:'FUNÇÕES HIDRAULICAS LENTAS'},
{codigo:12,itens:'CLAMPS LENTO'},
{codigo:13,itens:'DESLOCAMENT OLENTO'},
{codigo:14,itens:'PROBLEMA MECANICO TORRE'},
{codigo:15,itens:'MARCADOR DE COMBUSTIVEL'},
{codigo:16,itens:'AR CONDICIONADO'},
{codigo:17,itens:'BANCO DO OPERADOR'},
{codigo:18,itens:'FECHADURAS PORTAS'},
{codigo:19,itens:'RETROVISOR'},
{codigo:20,itens:'PARA BRISA'},
{codigo:21,itens:'VIDRO PORTA'},
{codigo:22,itens:'VIDRO TRASEIRO'},
{codigo:23,itens:'VIDRO SUPERIOR'},
{codigo:24,itens:'ILUMINAÇÃO'},
{codigo:25,itens:'FALHA ELETRICA MOTOR'},
{codigo:26,itens:'FALHA ELETRICA TRANSMISSÃO'},
{codigo:27,itens:'VAZAMENTOS HIDRAULICO'},
{codigo:28,itens:'VAZAMENTO CLAMPS'},
{codigo:29,itens:'VAZAMENTO RODA TRAÇÃO'},
{codigo:30,itens:'VAZAMENTO DE AR'},
{codigo:31,itens:'AQUECIMENTO MOTOR'},
{codigo:32,itens:'AQUECIMENTO TRANSMISSÃO'},
{codigo:33,itens:'FALTA DE COMBUSTIVEL'},
{codigo:34,itens:'SOLDA'},
{codigo:35,itens:'RODA FROUXA'},
{codigo:36,itens:'RODA QUEBRADA'},
{codigo:37,itens:'TRAVANDO FARDO'},
{codigo:38,itens:'SOLTANDO FARDO'},
{codigo:39,itens:'AVARIA OPERACIONAL'},
{codigo:40,itens:'FALHA MECANICA CLAMPS'},
{codigo:41,itens:'FALHA MECANICA MOTOR'},
{codigo:42,itens:'FALHA MECANICA TRANSMISSÃO'},
{codigo:43,itens:'PROBLEMA MECANICO ENGATE'},
{codigo:44,itens:'COMPLETAR OLEO'},
{codigo:48,itens:'REAPERTO'},
{codigo:50,itens:'REFORMA'},
{codigo:'',itens:''},
{codigo:'',itens:''}
  ]
